# Compile docker then build and test the project
name: Build and Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run docker-compose
        run: cd src/main/resources && docker-compose up -d
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run tests
        run: ./gradlew test
      - name: Run integration tests
        run: ./gradlew integrationTest
      - name: Stop docker-compose
        run: docker-compose down
