# Compile docker then build and test the project
name: Build and Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run docker-compose
        run: cd src/main/resources && docker-compose up -d && cd ../../../../

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build with Gradle
        env:
          DATABASE_URL: jdbc:postgresql://localhost:5432/postgres
          DATABASE_USERNAME: postgres
          DATABASE_PASSWORD: postgres
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Stop docker-compose
        run: docker-compose down
