# Compile docker then build and test the project

name: Build and Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run docker-compose
        run: cd src/main/resources && docker-compose up -d && cd ../../../../

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Grant file permissions for postgres-data then build with Gradle
        env:
          DATABASE_URL: jdbc:postgresql://localhost:5432/postgres
          DATABASE_USERNAME: postgres
          DATABASE_PASSWORD: postgres
        run: sudo chown -R 999:999 src/main/resources/postgres-data && sudo chmod -R 777 src/main/resources/postgres-data && ./gradlew build

      - name: Grant file permissions for postgres-data then run tests
        run: sudo chown -R 999:999 src/main/resources/postgres-data && sudo chmod -R 777 src/main/resources/postgres-data && ./gradlew test

      - name: Stop docker-compose
        run: docker-compose down
